<a href="https://colab.research.google.com/github/yiruchen1993/blog-practice/blob/master/tensorflow_practice_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

安裝 TensorFlow, 2.0 無 tf.InteractiveSession()

In [0]:
import tensorflow as tf

In [0]:
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [0]:
tf.compat.v1.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


zero 張量

In [0]:
tf.zeros(2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [0]:
a = tf.zeros(2)
a

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [0]:
a = tf.zeros((2,3))
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

將任意值(0,1以外)填入張量

In [0]:
b = tf.fill((2, 2), value=5)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 5],
       [5, 5]], dtype=int32)>

建立常數張量

In [0]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

隨機抽樣

In [0]:
a = tf.random.normal([2,2], 0, 1, tf.float32, seed=1)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ],
       [ 0.06532937, -2.4427042 ]], dtype=float32)>

In [0]:
a = tf.random.uniform((2,2), -10, 10)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-7.5798464, -5.3117037],
       [ 3.6086864, -5.4361057]], dtype=float32)>

張量相加、伸縮

In [0]:
c = tf.ones((2, 2))
d = tf.ones((2, 2))
e = c + d
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [0]:
f = 2 * e
f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

非矩陣乘法是逐元素乘法

In [0]:
c = tf.fill((2, 2), 2)
d = tf.fill((2, 2), 7)
e = c * d
e

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 14],
       [14, 14]], dtype=int32)>

建立單位矩陣

In [0]:
a = tf.eye(4)
a

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

建立對角矩陣

In [0]:
r  = tf.range(1, 5, 1)
r

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [0]:
d = tf.linalg.diag(r)
d

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [0]:
a = tf.ones((2, 3))
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

矩陣轉置

In [0]:
at = tf.transpose(a)
at

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

矩陣乘法

In [0]:
a = tf.ones((2, 3))
b = tf.ones((3, 4))
c = tf.matmul(a, b)
c

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>

張量型態

In [0]:
a = tf.ones((2, 2), dtype=tf.int32)
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [0]:
a = tf.ones((2, 2), dtype=tf.int64)
a

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1]])>

轉換函式

In [0]:
b = tf.compat.v1.to_float(a)
b

Instructions for updating:
Use `tf.cast` instead.


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [0]:
b = tf.cast(a, dtype=float)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

改變張量形狀

In [0]:
a = tf.ones(8)
b = tf.reshape(a, (4, 2))
b

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [0]:
c = tf.reshape(a, (2, 2, 2))
c

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

取得形狀

In [0]:
a = tf.ones(2)
a.get_shape()

TensorShape([2])

為張量多加一維度

In [0]:
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([1, 2])

In [0]:
b

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [0]:
c = tf.expand_dims(a, 1)
c.get_shape()

TensorShape([2, 1])

In [0]:
c

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

張量的維度移除1

In [0]:
d = tf.squeeze(b)
d.get_shape()

TensorShape([2])

In [0]:
d

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

broadcasting: 不同尺寸的矩陣和向量可以相加

In [0]:
a = tf.ones((2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [0]:
b = tf.range(0, 2, 1)
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

型態不會自動轉換

In [0]:
c = a + b

InvalidArgumentError: ignored

In [0]:
b = tf.range(0, 2, 1, dtype=float)
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>

In [0]:
c = a + b
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [1., 2.]], dtype=float32)>

當沒有明確指定tf.graph時，TensorFlow會隱藏的實例中加入張亮與運算，可用tf.Graph()取得實例

In [0]:
tf.Graph()

tf.Variable()類別可包裝張量來執行有狀態的計算。variable物件是張量的容器

In [0]:
a = tf.Variable(tf.ones((2, 2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [0]:
a.assign((tf.zeros((2, 2))))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [0]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

形狀不同時會失敗

In [0]:
a.assign((tf.zeros((2, 3))))

ValueError: ignored